"use client";
import { motion, useMotionValue } from "framer-motion";
import { useRef, useEffect, useState } from "react";

interface ImpactCard {
  image: string;
  title: string;
  description: string;
  impact: string;
  theme?: string;
}

const impacts: ImpactCard[] = [
  {
    image: "/images/woman-with-gauge.webp",
    title: "Women Measuring Climate Data",
    description: "Female farmers are at the forefront of our data collection efforts, using calibrated rain gauges to record accurate rainfall measurements. This hands-on involvement empowers women to become climate data experts in their communities, bridging the gap where they produce 70% of food but historically owned only 8% of agricultural resources.",
    impact: "50% women in leadership & data collection",
    theme: "#92672f",
  },
  {
    image: "/images/community-rain-gauge-installation.webp",
    title: "Building Local Weather Infrastructure",
    description: "Installing community-managed rain gauges across 14 communities in the Pra River Basin creates a hyperlocal weather monitoring network. These simple yet precise instruments enable farmers to validate indigenous forecasts with scientific data, forming the foundation of SIWA's AI learning system while ensuring climate information is generated by and for the community.",
    impact: "90+ community rain gauge stations",
    theme: "#343f22",
  },
  {
    image: "/images/women-in-agric-engagement-session.webp",
    title: "Co-Creating Climate Solutions",
    description: "Our co-production approach brings farmers, researchers, and agricultural officers together in collaborative workshops. Women and youth actively shape SIWA's features, ensuring the app reflects their real needs, from planting alerts to water management guidance. These sessions transform passive recipients into active innovators, documenting indigenous ecological indicators while building digital literacy and confidence.",
    impact: "4,000+ people benefit from improved yields",
    theme: "#9e958a",
  },
  {
    image: "/images/cocoa-farmer.webp",
    title: "Protecting Ghana's Cocoa Heritage",
    description: "Cocoa farming, which accounts for 70% of family income in the Pra River Basin, is highly vulnerable to rainfall variability. SIWA equips cocoa farmers with precise seasonal onset predictions and daily weather forecasts, helping them time critical activities like pod harvesting and fermentation. By combining their observations of Ceiba trees, moon phases, and animal behaviors with AI-enhanced forecasts, farmers reduce losses from unexpected weather.",
    impact: "30% reduction in weather-related crop losses",
    theme: "#635c61",
  },
  {
    image: "/images/field-training.webp",
    title: "From Traditional Wisdom to Digital Innovation",
    description: "Hands-on training sessions teach farmers to use SIWA's icon-driven interface, logging indigenous weather indicators like cloud patterns, frog croaking, and bamboo sounds alongside actual rainfall readings. These workshops bridge generational knowledge gaps—elders share forecasting wisdom validated through centuries of practice, while youth gain digital skills. With trainings in local languages and accessible designs, even farmers with limited literacy become confident app users.",
    impact: "500+ farmers trained across 3 regions",
    theme: "#6b4c59",
  },
];

export default function ActivitiesSection() {
  const trackRef = useRef<HTMLDivElement>(null);
  const [dragLimit, setDragLimit] = useState(0);
  const [activeIndex, setActiveIndex] = useState(0);
  const x = useMotionValue(0);

  useEffect(() => {
    if (!trackRef.current) return;
    const updateLimit = () => {
      setDragLimit(trackRef.current!.scrollWidth - trackRef.current!.offsetWidth + 100);
    };

    updateLimit();
    window.addEventListener("resize", updateLimit);
    return () => window.removeEventListener("resize", updateLimit);
  }, []);

  // Update active index based on horizontal scroll position
  useEffect(() => {
    return x.onChange((latest) => {
      // Calculate card width based on Tailwind classes (w-180 is 720px)
      const cardWidth = window.innerWidth < 768 ? window.innerWidth * 0.85 : 720;
      const index = Math.round(Math.abs(latest) / cardWidth);
      if (index !== activeIndex && index >= 0 && index < impacts.length) {
        setActiveIndex(index);
      }
    });
  }, [x, activeIndex]);

  return (
    <section id="impact" className="bg-white py-14 md:py-20 overflow-hidden">
      <div className="mb-12 text-center max-w-4xl mx-auto px-4">
        <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6 font-heading">
          Climate Resilience in Action.
        </h2>
        <p className="text-lg md:text-xl text-gray-600 leading-relaxed font-sans">
          SIWA is bridging indigenous wisdom and modern technology to transform smallholder farming across Ghana&apos;s Pra River Basin
        </p>
      </div>

      <div className="w-screen">
        <motion.div
          ref={trackRef}
          drag="x"
          style={{ x }}
          dragConstraints={{ left: -dragLimit, right: 0 }}
          dragElastic={0.06}
          className="flex gap-6 md:gap-8 px-4 md:px-12 cursor-grab active:cursor-grabbing"
        >
          {impacts.map((impact, index) => (
            <Card 
              key={index} 
              impact={impact} 
              isActive={activeIndex === index} 
            />
          ))}
        </motion.div>
      </div>

      <div className="text-center mt-12 px-4">
        <p className="text-sm md:text-base text-gray-500 italic font-sans">
          Real impact from communities across Ashanti, Eastern, and Central regions
        </p>
      </div>
    </section>
  );
}

function Card({ impact, isActive }: { impact: ImpactCard; isActive: boolean }) {
  return (
    <motion.div
      initial="collapsed"
      animate={isActive ? "expanded" : "collapsed"}
      whileHover="expanded"
      className="relative shrink-0 w-[85vw] sm:w-[65vw] md:w-180 aspect-4/5 md:aspect-5/3 rounded-3xl overflow-hidden bg-gray-100 shadow-xl transition-all duration-500"
    >
      <motion.div
        variants={{
          collapsed: { scale: 1 },
          expanded: { scale: 1.05 },
        }}
        transition={{ duration: 0.6, ease: [0.33, 1, 0.68, 1] }}
        className="absolute inset-0 bg-cover bg-center"
        style={{ backgroundImage: `url(${impact.image})` }}
      />

      <div
        className="absolute inset-0"
        style={{
          background: `linear-gradient(to top, ${
            impact.theme || "#000"
          } 0%, rgba(0,0,0,0.4) 60%, transparent 100%)`,
        }}
      />

      <div className="absolute bottom-0 inset-x-0 p-6 md:p-8 lg:p-10 flex flex-col justify-end">
        <div className="relative z-10">
          <span className="inline-block mb-3 px-4 py-1.5 rounded-full text-xs font-sans text-white bg-white/20 backdrop-blur-md border border-white/20 shadow-xs">
            {impact.impact}
          </span>
          <h3 className="text-xl md:text-2xl lg:text-3xl font-bold font-heading text-white leading-tight drop-shadow-xs">
            {impact.title}
          </h3>
        </div>
        
        <motion.div
          variants={{
            collapsed: { height: 0, opacity: 0, marginTop: 0 },
            expanded: { height: "auto", opacity: 1, marginTop: 12 },
          }}
          transition={{ duration: 0.4, ease: [0.33, 1, 0.68, 1] }}
          className="overflow-hidden"
        >
          <p className="text-white/90 text-xs md:text-sm font-sans max-w-2xl">
            {impact.description}
          </p>
        </motion.div>
      </div>
    </motion.div>
  );
}
